### ISSUE TITLE
LogInfo  not in Dm.filter

### ISSUE THREAD

**Issue by leconehu** [dmdbms/DmProvider#2]
using Dm.filter.log;
using Dm.filter.reconnect;
using Dm.filter.rw;

namespace Dm.filter
{
	internal interface IFilterInfo
	{
		long ID { get; }

		FilterChain FilterChain { get; set; }

		LogInfo LogInfo { get; set; }

		RWInfo RWInfo { get; set; }

		RecoverInfo RecoverInfo { get; set; }
	}
}

![image](https://user-images.githubusercontent.com/34261440/160365944-4f37af00-ee7c-46c9-9de1-6caf67bd8b24.png)

**Comment by aaasoft** [comment]
感谢反馈，是DmProvider/Dm/filter/log目录默认被.gitignore文件排除了，现在文件已经都提交上来了。

[commit b74d93fd4f1e2ce5e03d26679405aba74d8987c3](https://github.com/dmdbms/DmProvider/commit/b74d93fd4f1e2ce5e03d26679405aba74d8987c3)
