### ISSUE TITLE
同一个连接对象关闭再打开后执行操作出错

### ISSUE THREAD

**Issue by jadonhuang** [dmdbms/DmProvider#4]
var connection = new DmConnection("Server=127.0.0.1; UserId=TEST; PWD=123456789");
connection.Open();

 var command = connection.CreateCommand();
command.CommandText = @"SELECT count(1) FROM users";

var obj = command.ExecuteScalar();

//这两句注释掉就没有问题
connection.Close();
connection.Open();

command = connection.CreateCommand();
command.CommandText = @"SELECT count(1) FROM users";
obj = command.ExecuteScalar();   这里报： System.ArgumentException:“Source array was not long enough. Check the source index, length, and the array's lower bounds. Arg_ParamName_Name”

**Comment by aaasoft** [comment]
看起来是连接关闭后再打开，再执行SQL命令的时候会出错。我这边最近没有弄达梦的开发，没有测试环境。欢迎你Fork一份仓库测试一下找到问题，修复后合并进来。

**Comment by aaasoft** [comment]
我把达梦最新的dll打包发到NuGet上了，你试试看呢。
https://www.nuget.org/packages/dmdbms.DmProvider/1.1.0.16649
