### ISSUE TITLE
在进行修改时出现了超时问题！

### ISSUE THREAD

**Issue by adminoryuan** [dmdbms/DmProvider#5]

**Comment by aaasoft** [comment]
版本号，使用代码、异常堆栈。啥都没有。。。

**Comment by adminoryuan** [comment]
在Dm管理工具的执行是正常的  
该语句会超时。。
`

UPDATE table1

SET table1.PoPmAllQty=(SELECT COUNT(1) FROM table2 WHERE table2.code LIKE T1.code||'%' AND table2.IsDelete='IsDelete_No')

,table1.qty=(SELECT COUNT(1) FROM table2 WHERE table2.code LIKE T1.code||'%')

FROM table1 AS T1

`
  `using (var connection = new DmConnection(connectionString))
            {
                using (var cmd = new DmCommand())
                {
                    try
                    {
                        cmd.CommandTimeout = commandTimeout;//设置执行超时时间
                        int rows = cmd.ExecuteNonQuery();
                        cmd.Parameters.Clear();
                        return rows;
                    }
                    catch (DmException e)
                    {
                        throw e;
                    }
                }
            }`

**Comment by aaasoft** [comment]
是使用的1.1.0.16649版本吗？1.1.0.16649这个版本是从达梦的安装包里提取出来的。如果还有问题，建议联系达梦官方的技术支持哈。
